redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
publish = "C:\\Users\\Admin\\Desktop\\managing_app-7318a82e87c1a12ee55ead5448cf53c39d1822d6\\dist\\newstalgia\\browser"
publishOrigin = "inline"
commandOrigin = "config"
command = "npm run build"
base = "C:\\Users\\Admin\\Desktop\\managing_app-7318a82e87c1a12ee55ead5448cf53c39d1822d6"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]